import{useEffect,useMemo,useState}from'react';
type Dose={medicine_id:number;medicine_time_id:number;name:string;notes?:string;time:string;status?:'taken'|'missed';actual_taken_at?:string};
type Med={id:number;name:string;notes?:string;active:number;start_date?:string;end_date?:string;times:string[]};
const localDate=()=>{const d=new Date(),o=d.getTimezoneOffset();return new Date(d.getTime()-o*60000).toISOString().slice(0,10)};
const localDT=()=>{const d=new Date(),o=d.getTimezoneOffset();return new Date(d.getTime()-o*60000).toISOString().slice(0,16)};
const fmt=(t:string)=>new Date('2000-01-01T'+t).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});
const api=async(url:string,opt?:RequestInit)=>{const r=await fetch(url,opt);const j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j};
export default function App(){const[tab,setTab]=useState<'today'|'meds'>('today');const[doses,setDoses]=useState<Dose[]>([]);const[meds,setMeds]=useState<Med[]>([]);const[actual,setActual]=useState(localDT());const[busy,setBusy]=useState(false);const[editing,setEditing]=useState<Partial<Med>|null>(null);
const load=async()=>{setDoses(await api('/api/day?date='+localDate()));setMeds(await api('/api/medicines'))};useEffect(()=>{load()},[]);
const now=new Date().toTimeString().slice(0,5);const pending=doses.filter(x=>!x.status);const next=useMemo(()=>pending.find(x=>x.time>=now)||pending[0],[doses,now]);const done=doses.filter(x=>x.status);
useEffect(()=>{setActual(localDT())},[next?.medicine_id,next?.time]);
const mark=async(d:Dose,status:'taken'|'missed')=>{setBusy(true);try{await api('/api/doses',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...d,scheduled_date:localDate(),scheduled_time:d.time,status,actual_taken_at:status==='taken'?new Date(actual).toISOString():null})});await load()}finally{setBusy(false)}};
const save=async()=>{if(!editing?.name||!editing.times?.length)return;setBusy(true);try{const body=JSON.stringify({...editing,active:editing.active??1});await api(editing.id?'/api/medicines/'+editing.id:'/api/medicines',{method:editing.id?'PUT':'POST',headers:{'content-type':'application/json'},body});setEditing(null);await load()}finally{setBusy(false)}};
return <main className="mx-auto max-w-xl min-h-screen px-4 py-6">
<header className="mb-7 flex items-center justify-between"><div><h1 className="text-xl font-semibold">Medicine</h1><p className="text-sm text-slate-500">{new Date().toLocaleDateString([],{weekday:'long',day:'numeric',month:'long'})}</p></div><button onClick={()=>setTab(tab==='today'?'meds':'today')} className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm">{tab==='today'?'Manage':'Today'}</button></header>
{tab==='today'?<>{next?<section className="rounded-3xl bg-white border border-slate-200 p-6 mb-7"><p className="text-xs font-semibold uppercase tracking-widest text-slate-400">Next medicine</p><div className="mt-2 flex items-end justify-between gap-3"><div><h2 className="text-3xl font-bold">{next.name}</h2><p className="mt-1 text-slate-500">{next.notes}</p></div><div className="text-2xl font-semibold whitespace-nowrap">{fmt(next.time)}</div></div>
<label className="mt-7 block text-sm text-slate-500">Actually taken at</label><input type="datetime-local" value={actual} onChange={e=>setActual(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 bg-slate-50 p-3 text-base"/>
<button disabled={busy} onClick={()=>mark(next,'taken')} className="mt-4 w-full rounded-2xl bg-slate-900 py-4 text-lg font-semibold text-white">✓ Confirm taken</button><button disabled={busy} onClick={()=>mark(next,'missed')} className="mt-2 w-full py-3 text-sm text-slate-500">Mark as missed</button></section>:<section className="rounded-3xl bg-white border border-slate-200 p-8 text-center mb-7"><div className="text-3xl">✓</div><h2 className="mt-2 text-xl font-semibold">All done for today</h2></section>}
<section><h3 className="mb-3 font-semibold">Today's schedule</h3><div className="divide-y divide-slate-200 rounded-2xl border border-slate-200 bg-white">{doses.map((d,i)=><div key={i} className="flex items-center gap-3 px-4 py-3"><span className="w-20 text-sm font-medium">{fmt(d.time)}</span><span className={'flex-1 '+(d.status?'text-slate-400':'')}>{d.name}</span><span className={'text-xs font-medium '+(d.status==='taken'?'text-emerald-600':d.status==='missed'?'text-rose-500':'text-slate-400')}>{d.status==='taken'?'Taken':d.status==='missed'?'Missed':d.time<now?'Due':'Upcoming'}</span></div>)}</div></section></>:
<section><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-semibold">Medicines & schedules</h2><button onClick={()=>setEditing({name:'',notes:'',times:['08:00'],active:1})} className="rounded-xl bg-slate-900 px-4 py-2 text-sm text-white">+ Add</button></div>
<div className="space-y-3">{meds.map(m=><div key={m.id} className={'rounded-2xl border border-slate-200 bg-white p-4 '+(!m.active?'opacity-50':'')}><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{m.name}</h3><p className="mt-1 text-sm text-slate-500">{m.times.map(fmt).join(' · ')}</p></div><button onClick={()=>setEditing({...m})} className="text-sm font-medium">Edit</button></div></div>)}</div></section>}
{editing&&<div className="fixed inset-0 z-10 flex items-end bg-black/30 sm:items-center sm:justify-center"><div className="w-full max-w-lg rounded-t-3xl bg-white p-5 sm:rounded-3xl"><div className="mb-5 flex justify-between"><h2 className="text-lg font-semibold">{editing.id?'Edit medicine':'Add medicine'}</h2><button onClick={()=>setEditing(null)}>✕</button></div>
<label className="text-sm text-slate-500">Medicine name</label><input value={editing.name||''} onChange={e=>setEditing({...editing,name:e.target.value})} className="mb-4 mt-1 w-full rounded-xl border border-slate-200 p-3"/>
<label className="text-sm text-slate-500">Notes</label><input value={editing.notes||''} onChange={e=>setEditing({...editing,notes:e.target.value})} className="mb-4 mt-1 w-full rounded-xl border border-slate-200 p-3"/>
<div className="mb-2 flex justify-between"><label className="text-sm text-slate-500">Daily times</label><button onClick={()=>setEditing({...editing,times:[...(editing.times||[]),'12:00']})} className="text-sm font-medium">+ Time</button></div>
<div className="space-y-2">{editing.times?.map((t,i)=><div className="flex gap-2" key={i}><input type="time" value={t} onChange={e=>{const a=[...(editing.times||[])];a[i]=e.target.value;setEditing({...editing,times:a})}} className="flex-1 rounded-xl border border-slate-200 p-3"/><button onClick={()=>setEditing({...editing,times:editing.times?.filter((_,x)=>x!==i)})} className="px-3 text-slate-400">Remove</button></div>)}</div>
<div className="mt-4 grid grid-cols-2 gap-2"><div><label className="text-xs text-slate-500">Start date (optional)</label><input type="date" value={editing.start_date||''} onChange={e=>setEditing({...editing,start_date:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 p-3"/></div><div><label className="text-xs text-slate-500">End date (optional)</label><input type="date" value={editing.end_date||''} onChange={e=>setEditing({...editing,end_date:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 p-3"/></div></div>
{editing.id&&<label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={!!editing.active} onChange={e=>setEditing({...editing,active:e.target.checked?1:0})}/> Active</label>}
<button disabled={busy||!editing.name||!editing.times?.length} onClick={save} className="mt-5 w-full rounded-2xl bg-slate-900 py-4 font-semibold text-white disabled:opacity-40">Save medicine</button></div></div>}</main>}